package org.upb.data;
// Generated 31 ao�t 2022 � 12:53:26 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Absence generated by hbm2java
 */
@Entity
@Table(name = "absence", catalog = "upb")
public class Absence implements java.io.Serializable {

	private Integer idAbsence;
	private Ecue ecue;
	private Enseignant enseignant;
	private Etudiant etudiant;
	private byte statusAbsence;
	private byte etatAbsence;
	private Date dateAbsence;
	private String heureDebut;
	private String heureFin;
	private Set<Justification> justifications = new HashSet<Justification>(0);

	public Absence() {
	}

	public Absence(Ecue ecue, Enseignant enseignant, Etudiant etudiant, byte statusAbsence, byte etatAbsence,
			Date dateAbsence, String heureDebut, String heureFin) {
		this.ecue = ecue;
		this.enseignant = enseignant;
		this.etudiant = etudiant;
		this.statusAbsence = statusAbsence;
		this.etatAbsence = etatAbsence;
		this.dateAbsence = dateAbsence;
		this.heureDebut = heureDebut;
		this.heureFin = heureFin;
	}

	public Absence(Ecue ecue, Enseignant enseignant, Etudiant etudiant, byte statusAbsence, byte etatAbsence,
			Date dateAbsence, String heureDebut, String heureFin, Set<Justification> justifications) {
		this.ecue = ecue;
		this.enseignant = enseignant;
		this.etudiant = etudiant;
		this.statusAbsence = statusAbsence;
		this.etatAbsence = etatAbsence;
		this.dateAbsence = dateAbsence;
		this.heureDebut = heureDebut;
		this.heureFin = heureFin;
		this.justifications = justifications;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)

	@Column(name = "id_absence", unique = true, nullable = false)
	public Integer getIdAbsence() {
		return this.idAbsence;
	}

	public void setIdAbsence(Integer idAbsence) {
		this.idAbsence = idAbsence;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ECUE_id_ue", nullable = false)
	public Ecue getEcue() {
		return this.ecue;
	}

	public void setEcue(Ecue ecue) {
		this.ecue = ecue;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Enseignant_id_Enseignant", nullable = false)
	public Enseignant getEnseignant() {
		return this.enseignant;
	}

	public void setEnseignant(Enseignant enseignant) {
		this.enseignant = enseignant;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Etudiant_matricule_etudiant", nullable = false)
	public Etudiant getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

	@Column(name = "status_absence", nullable = false)
	public byte getStatusAbsence() {
		return this.statusAbsence;
	}

	public void setStatusAbsence(byte statusAbsence) {
		this.statusAbsence = statusAbsence;
	}

	@Column(name = "etat_absence", nullable = false)
	public byte getEtatAbsence() {
		return this.etatAbsence;
	}

	public void setEtatAbsence(byte etatAbsence) {
		this.etatAbsence = etatAbsence;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_absence", nullable = false, length = 10)
	public Date getDateAbsence() {
		return this.dateAbsence;
	}

	public void setDateAbsence(Date dateAbsence) {
		this.dateAbsence = dateAbsence;
	}

	@Column(name = "heure_debut", nullable = false, length = 45)
	public String getHeureDebut() {
		return this.heureDebut;
	}

	public void setHeureDebut(String heureDebut) {
		this.heureDebut = heureDebut;
	}

	@Column(name = "heure_fin", nullable = false, length = 45)
	public String getHeureFin() {
		return this.heureFin;
	}

	public void setHeureFin(String heureFin) {
		this.heureFin = heureFin;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "absence")
	public Set<Justification> getJustifications() {
		return this.justifications;
	}

	public void setJustifications(Set<Justification> justifications) {
		this.justifications = justifications;
	}

}
