package org.upb.data;
// Generated 31 ao�t 2022 � 12:53:26 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AnneeAcademique generated by hbm2java
 */
@Entity
@Table(name = "annee_academique", catalog = "heroku_88ae11bd39df693")
public class AnneeAcademique implements java.io.Serializable {

	private Integer idAnneeAcademique;
	private Semestre semestre;
	private Date dateDebut;
	private Date dateFin;

	public AnneeAcademique() {
	}

	public AnneeAcademique(Semestre semestre, Date dateDebut, Date dateFin) {
		this.semestre = semestre;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)

	@Column(name = "id_annee_academique", unique = true, nullable = false)
	public Integer getIdAnneeAcademique() {
		return this.idAnneeAcademique;
	}

	public void setIdAnneeAcademique(Integer idAnneeAcademique) {
		this.idAnneeAcademique = idAnneeAcademique;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Semestre_id_semestre", nullable = false)
	public Semestre getSemestre() {
		return this.semestre;
	}

	public void setSemestre(Semestre semestre) {
		this.semestre = semestre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_debut", nullable = false, length = 10)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_fin", nullable = false, length = 10)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

}
