package org.upb.data;
// Generated 1 sept. 2022 � 12:20:27 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AnneeAcademique generated by hbm2java
 */
@Entity
@Table(name = "annee_academique", catalog = "heroku_88ae11bd39df693")
public class AnneeAcademique implements java.io.Serializable {

	private Integer idAnneeAcademique;
	private Date dateDebut;
	private Date dateFin;
	private Set<Semestre> semestres = new HashSet<Semestre>(0);

	public AnneeAcademique() {
	}

	public AnneeAcademique(Date dateDebut, Date dateFin) {
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
	}

	public AnneeAcademique(Date dateDebut, Date dateFin, Set<Semestre> semestres) {
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.semestres = semestres;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)

	@Column(name = "id_annee_academique", unique = true, nullable = false)
	public Integer getIdAnneeAcademique() {
		return this.idAnneeAcademique;
	}

	public void setIdAnneeAcademique(Integer idAnneeAcademique) {
		this.idAnneeAcademique = idAnneeAcademique;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_debut", nullable = false, length = 10)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_fin", nullable = false, length = 10)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "anneeAcademique")
	public Set<Semestre> getSemestres() {
		return this.semestres;
	}

	public void setSemestres(Set<Semestre> semestres) {
		this.semestres = semestres;
	}

}
