package org.upb.data;
// Generated 31 ao�t 2022 � 12:53:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Enseignant generated by hbm2java
 */
@Entity
@Table(name = "enseignant", catalog = "heroku_88ae11bd39df693")
public class Enseignant implements java.io.Serializable {

	private Integer idEnseignant;
	private String specialiteEnseignant;
	private String emailEnseignant;
	private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);
	private Set<Absence> absences = new HashSet<Absence>(0);

	public Enseignant() {
	}

	public Enseignant(String specialiteEnseignant, String emailEnseignant) {
		this.specialiteEnseignant = specialiteEnseignant;
		this.emailEnseignant = emailEnseignant;
	}

	public Enseignant(String specialiteEnseignant, String emailEnseignant, Set<Utilisateur> utilisateurs,
			Set<Absence> absences) {
		this.specialiteEnseignant = specialiteEnseignant;
		this.emailEnseignant = emailEnseignant;
		this.utilisateurs = utilisateurs;
		this.absences = absences;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)

	@Column(name = "id_Enseignant", unique = true, nullable = false)
	public Integer getIdEnseignant() {
		return this.idEnseignant;
	}

	public void setIdEnseignant(Integer idEnseignant) {
		this.idEnseignant = idEnseignant;
	}

	@Column(name = "specialite_enseignant", nullable = false, length = 45)
	public String getSpecialiteEnseignant() {
		return this.specialiteEnseignant;
	}

	public void setSpecialiteEnseignant(String specialiteEnseignant) {
		this.specialiteEnseignant = specialiteEnseignant;
	}

	@Column(name = "email_enseignant", nullable = false, length = 45)
	public String getEmailEnseignant() {
		return this.emailEnseignant;
	}

	public void setEmailEnseignant(String emailEnseignant) {
		this.emailEnseignant = emailEnseignant;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "enseignant")
	public Set<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "enseignant")
	public Set<Absence> getAbsences() {
		return this.absences;
	}

	public void setAbsences(Set<Absence> absences) {
		this.absences = absences;
	}

}
