package org.upb.data;
// Generated 31 ao�t 2022 � 12:53:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Filiere generated by hbm2java
 */
@Entity
@Table(name = "filiere", catalog = "heroku_88ae11bd39df693")
public class Filiere implements java.io.Serializable {

	private Integer idFiliere;
	private String designationFiliere;
	private Set<Etudiant> etudiants = new HashSet<Etudiant>(0);

	public Filiere() {
	}

	public Filiere(String designationFiliere) {
		this.designationFiliere = designationFiliere;
	}

	public Filiere(String designationFiliere, Set<Etudiant> etudiants) {
		this.designationFiliere = designationFiliere;
		this.etudiants = etudiants;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)

	@Column(name = "id_filiere", unique = true, nullable = false)
	public Integer getIdFiliere() {
		return this.idFiliere;
	}

	public void setIdFiliere(Integer idFiliere) {
		this.idFiliere = idFiliere;
	}

	@Column(name = "designation_filiere", nullable = false, length = 45)
	public String getDesignationFiliere() {
		return this.designationFiliere;
	}

	public void setDesignationFiliere(String designationFiliere) {
		this.designationFiliere = designationFiliere;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "filiere")
	public Set<Etudiant> getEtudiants() {
		return this.etudiants;
	}

	public void setEtudiants(Set<Etudiant> etudiants) {
		this.etudiants = etudiants;
	}

}
