package org.upb.data;
// Generated 31 ao�t 2022 � 12:53:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Niveau generated by hbm2java
 */
@Entity
@Table(name = "niveau", catalog = "upb")
public class Niveau implements java.io.Serializable {

	private Integer idNiveau;
	private String designationNiveau;
	private String libelleNiveau;
	private Set<Administrateur> administrateurs = new HashSet<Administrateur>(0);
	private Set<Etudiant> etudiants = new HashSet<Etudiant>(0);

	public Niveau() {
	}

	public Niveau(String designationNiveau, String libelleNiveau, Set<Administrateur> administrateurs,
			Set<Etudiant> etudiants) {
		this.designationNiveau = designationNiveau;
		this.libelleNiveau = libelleNiveau;
		this.administrateurs = administrateurs;
		this.etudiants = etudiants;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)

	@Column(name = "id_niveau", unique = true, nullable = false)
	public Integer getIdNiveau() {
		return this.idNiveau;
	}

	public void setIdNiveau(Integer idNiveau) {
		this.idNiveau = idNiveau;
	}

	@Column(name = "designation_niveau", length = 45)
	public String getDesignationNiveau() {
		return this.designationNiveau;
	}

	public void setDesignationNiveau(String designationNiveau) {
		this.designationNiveau = designationNiveau;
	}

	@Column(name = "libelle_niveau", length = 45)
	public String getLibelleNiveau() {
		return this.libelleNiveau;
	}

	public void setLibelleNiveau(String libelleNiveau) {
		this.libelleNiveau = libelleNiveau;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "niveau")
	public Set<Administrateur> getAdministrateurs() {
		return this.administrateurs;
	}

	public void setAdministrateurs(Set<Administrateur> administrateurs) {
		this.administrateurs = administrateurs;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "niveau")
	public Set<Etudiant> getEtudiants() {
		return this.etudiants;
	}

	public void setEtudiants(Set<Etudiant> etudiants) {
		this.etudiants = etudiants;
	}

}
