package org.upb.data;
// Generated 1 sept. 2022 � 12:20:27 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Semestre generated by hbm2java
 */
@Entity
@Table(name = "semestre", catalog = "heroku_88ae11bd39df693")
public class Semestre implements java.io.Serializable {

	private Integer idSemestre;
	private AnneeAcademique anneeAcademique;
	private String libelleSemestre;
	private Set<Ecue> ecues = new HashSet<Ecue>(0);

	public Semestre() {
	}

	public Semestre(AnneeAcademique anneeAcademique, String libelleSemestre) {
		this.anneeAcademique = anneeAcademique;
		this.libelleSemestre = libelleSemestre;
	}

	public Semestre(AnneeAcademique anneeAcademique, String libelleSemestre, Set<Ecue> ecues) {
		this.anneeAcademique = anneeAcademique;
		this.libelleSemestre = libelleSemestre;
		this.ecues = ecues;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)

	@Column(name = "id_semestre", unique = true, nullable = false)
	public Integer getIdSemestre() {
		return this.idSemestre;
	}

	public void setIdSemestre(Integer idSemestre) {
		this.idSemestre = idSemestre;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Annee_academique_id_annee_academique", nullable = false)
	public AnneeAcademique getAnneeAcademique() {
		return this.anneeAcademique;
	}

	public void setAnneeAcademique(AnneeAcademique anneeAcademique) {
		this.anneeAcademique = anneeAcademique;
	}

	@Column(name = "libelle_semestre", nullable = false, length = 45)
	public String getLibelleSemestre() {
		return this.libelleSemestre;
	}

	public void setLibelleSemestre(String libelleSemestre) {
		this.libelleSemestre = libelleSemestre;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "semestre_has_ecue", catalog = "heroku_88ae11bd39df693", joinColumns = {
			@JoinColumn(name = "Semestre_id_semestre", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ECUE_id_ue", nullable = false, updatable = false) })
	public Set<Ecue> getEcues() {
		return this.ecues;
	}

	public void setEcues(Set<Ecue> ecues) {
		this.ecues = ecues;
	}

}
