package org.upb.data;
// Generated 31 ao�t 2022 � 12:53:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "utilisateur", catalog = "upb")
public class Utilisateur implements java.io.Serializable {

	private Integer idUtilisateur;
	private Administrateur administrateur;
	private Enseignant enseignant;
	private Etudiant etudiant;
	private Parent parent;
	private String nom;
	private String prenom;
	private String numero;
	private String login;
	private String passwordUtilisateur;
	private Set<Role> roles = new HashSet<Role>(0);

	public Utilisateur() {
	}

	public Utilisateur(String login, String passwordUtilisateur) {
		this.login = login;
		this.passwordUtilisateur = passwordUtilisateur;
	}

	public Utilisateur(Administrateur administrateur, Enseignant enseignant, Etudiant etudiant, Parent parent,
			String nom, String prenom, String numero, String login, String passwordUtilisateur, Set<Role> roles) {
		this.administrateur = administrateur;
		this.enseignant = enseignant;
		this.etudiant = etudiant;
		this.parent = parent;
		this.nom = nom;
		this.prenom = prenom;
		this.numero = numero;
		this.login = login;
		this.passwordUtilisateur = passwordUtilisateur;
		this.roles = roles;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)

	@Column(name = "id_utilisateur", unique = true, nullable = false)
	public Integer getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(Integer idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Administrateur_id_responsable")
	public Administrateur getAdministrateur() {
		return this.administrateur;
	}

	public void setAdministrateur(Administrateur administrateur) {
		this.administrateur = administrateur;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Enseignant_id_Enseignant")
	public Enseignant getEnseignant() {
		return this.enseignant;
	}

	public void setEnseignant(Enseignant enseignant) {
		this.enseignant = enseignant;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Etudiant_matricule_etudiant")
	public Etudiant getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Parent_id_parent")
	public Parent getParent() {
		return this.parent;
	}

	public void setParent(Parent parent) {
		this.parent = parent;
	}

	@Column(name = "nom", length = 45)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 45)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "numero", length = 45)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "login", nullable = false, length = 45)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password_utilisateur", nullable = false, length = 200)
	public String getPasswordUtilisateur() {
		return this.passwordUtilisateur;
	}

	public void setPasswordUtilisateur(String passwordUtilisateur) {
		this.passwordUtilisateur = passwordUtilisateur;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "utilisateur_has_role", catalog = "upb", joinColumns = {
			@JoinColumn(name = "Utilisateur_id_utilisateur", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Role_id_role", nullable = false, updatable = false) })
	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

}
